app.py
from flask import Flask, render_template
import extensions
import config
import controllers

# Initialize Flask app with the template folder address
app = Flask(__name__, template_folder='templates')

app.register_blueprint(controllers.main)
app.register_blueprint(controllers.reflection)
app.register_blueprint(controllers.profile)
app.register_blueprint(controllers.blog)


# Listen on external IPs

if __name__ == '__main__':
    # listen on external IPs
    app.run(host=config.env['host'], port=config.env['port'], debug=True)

controllers/__init__.py
from .main import *
from .reflection import *
from .profile import *
from .blog import *

controllers/blog.py
from flask import *
from extensions import connect_to_database

blog = Blueprint('blog', __name__, template_folder='templates')


@blog.route('/blog', methods=['GET', 'POST'])
def reflection_route():
    db = connect_to_database()
    cur = db.cursor()
    
    cur.execute('SELECT * FROM Blog WHERE Type = %s;' ('share'))
    blog_posts = cur.fetchall()

    # results = cur.fetchall()
    options = {"blog_posts":blog_posts}
    return render_template("reflection.html")

controllers/main.py
from flask import *

from extensions import connect_to_database

main = Blueprint('main', __name__, template_folder='templates')

@main.route('/login')
def main_login():
    return render_template('login.html')

@main.route('/')
def main_hello():
    # db = connect_to_database()
    # cur = db.cursor()
    # create_table_queries = open("create_tables.sql", "r")
    # cur.execute(create_table_queries)
    # results = cur.fetchall()

    return render_template("index.html")

controllers/profile.py
from flask import *

from extensions import connect_to_database

profile = Blueprint('profile', __name__, template_folder='templates')


@profile.route('/profile')
def reflection_route():
    # db = connect_to_database()
    # cur = db.cursor()
    # cur.execute('SELECT username, firstname FROM User')
    # results = cur.fetchall()
    return render_template("profile.html")

    #If method = Post 
    	#record reflection for student and add to table

controllers/reflection.py
from flask import *
from extensions import connect_to_database

reflection = Blueprint('reflection', __name__, template_folder='templates')


@reflection.route('/reflection', methods=['GET', 'POST'])
def reflection_route():
    db = connect_to_database()
    cur = db.cursor()
    if request.method == "POST":
        response = request.form.get("reflectionform")
		print response
    	cur.execute('INSERT INTO Blog (UserID, Content, Type) Values (%s, %s,%s);', (1, response, 'share'))
    db.close()
    # results = cur.fetchall()
    return render_template("reflection.html")

    #If method = Post 
    	#record reflection for student and add to table

    

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="description" content="Embarc Journey Map">
	<meta name="keywords" content="HTML,CSS,SQL,JavaScript">
	<meta name="author" content="">

    <title>Embarc</title>
</head>
<header>
	<!--<div class="navbar" >
	  <a href="#home">Home</a>
	  <a href="#news">News</a>
	  <a href="#contact">Contact</a>
	</div>-->
	<link rel="stylesheet" href="{{url_for('static', filename="css/base.css") }}" type="text/css">
</header>
<body>
  <div style="text-align:center;">
    {% block content %}{% endblock %}
  </div>
</body>
<footer>
	<!-- <p style="text-align:center;">Copyright 2017</p -->
</footer>

</html>

templates/blog.html
{% extends "base.html" %}
{% block content %}

{% for blog in blog_posts %}
	<h3>
		{{blog['BlogID']}}
	</h3>
    <p>
        {{blog['Content']}}
    </p>
    {% endfor %}

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}

<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Journey Map</title>
		<link rel="stylesheet" href="{{url_for('static', filename="css/styles.css") }}" type="text/css">
	</head>

	<body>
	  <script src="{{url_for('static', filename="js/script.js")}}"></script>
		<div>
			<canvas id="map_canvas"></canvas>
		</div>
	</body>
</html>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}

<!DOCTYPE html>
<html>
<style>
/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
    position: relative;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
}

.container {
    padding: 16px;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
    position: absolute;
    right: 25px;
    top: 0;
    color: #000;
    font-size: 35px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: red;
    cursor: pointer;
}

/* Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)}
    to {-webkit-transform: scale(1)}
}

@keyframes animatezoom {
    from {transform: scale(0)}
    to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
</style>
<body>

<h2>Modal Login Form</h2>

<button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button>

<div id="id01" class="modal">

  <form class="modal-content animate" action="/action_page.php">
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src="{{url_for('static', filename='img/img_avatar.png')}}" alt="Avatar" class="avatar">
    </div>

    <div class="container">
      <label><b>Username</b></label>
      <input type="text" placeholder="Enter Username" name="uname" required>

      <label><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" required>

      <button type="submit">Login</button>
      <input type="checkbox" checked="checked"> Remember me
    </div>

    <div class="container" style="background-color:#f1f1f1">
      <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
      <span class="psw">Forgot <a href="#">password?</a></span>
    </div>
  </form>
</div>

<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

</body>
</html>

{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block content %}

<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>My Profile</title>
	</head>

	<body>

	  <!-- Add icon library -->
		<link rel="stylesheet" href="{{url_for('static', filename='css/profile.css') }}">

		<div class="card">
		  <h1>Name</h1>
		  <p class="title">Student</p>
		  <p>School</p>
		  <a href="#"><i class="fa fa-dribbble"></i></a>
		  <a href="#"><i class="fa fa-twitter"></i></a>
		  <a href="#"><i class="fa fa-linkedin"></i></a>
		  <a href="#"><i class="fa fa-facebook"></i></a>
			<p> Goals: </p>
			<p> Skills: </p>
		</div>
	</body>
</html>

{% endblock %}

templates/reflection.html
{% extends "base.html" %}
{% block content %}
<head>
  <title>Reflection</title>
</head>
  <link rel = "stylesheet" type = "text/css" href = "{{url_for('static', filename="css/reflection.css") }}"/>
<body>
  <h1> After Journey Attendance Journal </h1>
  <div class = prompt>
    <p> Reflect on the journey you just experienced by responding to the following prompts. </p>
    <p> <b>Paragraph 1:</b> Describe the journey from start to finish - use descriptive language and names of individuals
        you met. <br> Describe your experience with vivid detail so someone that did not attend could
        experience it through your writing. </p>
    <p> <b>Paragraph 2:</b> Describe what you learned or what may have surprised you during the journey.<br> Describe the
        deeper connection to what you learned or practiced and how you may apply it to your life </p>
  </div>

  Enter your response here:<br>
  


 

  <form action="{{url_for('reflection.reflection_route')}}" method="POST">
    <input type="text" name ="reflectionform">
    </textarea>
    <input type="submit">

  </form>
</body>

{% endblock %}